
# Definir el argumento GDAL_VERSION
ARG GDAL_VERSION=3.10.2

# Usar el argumento en la imagen base
# https://github.com/OSGeo/gdal/pkgs/container/gdal/versions?filters%5Bversion_type%5D=tagged
FROM ghcr.io/osgeo/gdal:ubuntu-small-${GDAL_VERSION}


# Variables
ENV version_NUMPY=2.2.4 


# Instalar dependencias necesarias
RUN apt-get update && apt-get install -y \
    software-properties-common \
    python3-launchpadlib \
    && apt-get clean


# Actualizar los repositorios e instalar GDAL y sus dependencias
RUN apt-get update && apt-get install -y \
        gdal-bin \
        libgdal-dev \
        python3-gdal \
        python3-dev \
        python3-venv \
        build-essential \
        python3-pip \
        libproj-dev \
        libgeos-dev \
        && apt-get clean

# Establecer variables de entorno para GDAL
ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal

# Verificar la instalación de GDAL
RUN gdalinfo --version 
RUN echo  gdalinfo --version 

# Vrear entorno virtual de Python
RUN python3 -m venv ./gda_python_env

ENV PATH="./gda_python_env/bin:$PATH"


# Instalar la librería Python de GDAL
RUN pip3 install --no-cache-dir  numpy==$version_NUMPY wheel setuptools>=67
RUN pip3 install --no-cache-dir  gdal[numpy]=="$(gdal-config --version).*" --no-build-isolation

# Copiar el archivo de Python al contenedor
WORKDIR /app
COPY checkGDAL.py /app/

# Comando por defecto para ejecutar el archivo de Python
CMD ["python3", "checkGDAL.py"]