version: "3.9"

services:
  gdal-installer-from_gdal_image:
    build:
      context: .
      dockerfile: dockerfile_fromGDALImage
      args:
        GDAL_VERSION: "3.10.2"
    container_name: gdal_installer_container_fromGDALImage
    volumes:
      - .:/app  # Montar el directorio actual en el contenedor
    command: ["python3", "checkGDAL.py"]