services:
  postgis-installer-easy_install:
    user: "root" 
    build:
      context: .
      dockerfile: dockerfile_easyInstall
    container_name: postgis_installer_container_easyInstall
    ports:
    - "5432:5432"
    
    command: sh -c 'sh ./start.sh && 
                    python3 checkPOSTGIS.py &&
                    echo "PostgreSQL está en ejecución. Siguiendo los logs..." &&
                    tail -f /var/lib/postgresql/logfile'

    volumes:
      - ./postgis_data:/var/lib/postgresql/data:volume-nocopy # Persistencia de datos