# Usar una imagen base de Ubuntu Server
FROM ubuntu:22.04

# Establecer variables de entorno para evitar interacciones durante la instalación
ENV DEBIAN_FRONTEND=noninteractive

# Definir un argumento para la versión de GDAL
ARG GDAL_VERSION=3.10.2
ENV version_NUMPY=2.2.4 


# Actualizar el sistema e instalar dependencias necesarias
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    cmake \
    git \
    wget \
    curl \
    libtool \
    m4 \
    autoconf \
    automake \
    python3 \
    python3-pip \
    python3-dev \
    python3-dev \
    python3-venv \
    libproj-dev \
    libgeos-dev \
    libsqlite3-dev \
    libcurl4-openssl-dev \
    libpng-dev \
    libjpeg-dev \
    libgif-dev \
    liblzma-dev \
    libtiff-dev \
    libwebp-dev \
    libhdf5-dev \
    libnetcdf-dev \
    libopenjp2-7-dev \
    libpoppler-dev \
    libspatialite-dev \
    libfreexl-dev \
    libarmadillo-dev \
    libmysqlclient-dev \
    libpq-dev \
    libxerces-c-dev \
    libexpat1-dev \
    zlib1g-dev

# Clonar el repositorio de GDAL
RUN wget https://github.com/OSGeo/gdal/releases/download/v${GDAL_VERSION}/gdal-${GDAL_VERSION}.tar.gz \
    && tar -xzf gdal-${GDAL_VERSION}.tar.gz \
    && cd gdal-${GDAL_VERSION} 

# Crear y entrar en el directorio de construcción
WORKDIR /gdal-${GDAL_VERSION} 
RUN mkdir build
WORKDIR /gdal-${GDAL_VERSION}/build

# Configurar, construir e instalar GDAL
RUN cmake .. && \
    cmake --build . && \
    cmake --build . --target install

# Limpiar archivos temporales
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# Establecer variables de entorno para GDAL
ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal
ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH



# Verificar la instalación de GDAL
RUN gdalinfo --version 
RUN echo  gdalinfo --version 

# Vrear entorno virtual de Python
RUN python3 -m venv /gda_python_env
ENV PATH="/gda_python_env/bin:$PATH"


# Instalar la librería Python de GDAL
RUN pip3 install --no-cache-dir  numpy==${version_NUMPY}  wheel setuptools>=67
RUN pip3 install --no-cache-dir  gdal[numpy]=="$(gdal-config --version).*" --no-build-isolation

RUN python3 -c 'from osgeo import gdal_array'
# Copiar el archivo de Python al contenedor
WORKDIR /app
COPY checkGDAL.py /app/

# Comando por defecto para ejecutar el archivo de Python
# CMD ["python3", "checkGDAL.py"]