# Definir el argumento PG_Version
ARG PG_Version=17-3.5 
ARG PG_Version_int

# Usar una imagen base de postgis
FROM postgis/postgis:${PG_Version}
ARG PG_Version

# Establecer variables de entorno para evitar interacciones durante la instalación
ENV DEBIAN_FRONTEND=noninteractive
ENV PG_Version=${PG_Version}


# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    python3-pip \
    python3-venv \
    && rm -rf /var/lib/apt/lists/*

# Crear entorno virtual de Python
WORKDIR /app
RUN python3 -m venv ./pgis_python_env
ENV PATH="/app/pgis_python_env/bin:$PATH"

# Instalar la librería psycopg2-binary en el entorno virtual
RUN /app/pgis_python_env/bin/pip install --no-cache-dir psycopg2-binary

# Configurar PostgreSQL
ENV PGDATA=/var/lib/postgresql/data
USER postgres
WORKDIR /var/lib/postgresql

RUN mkdir -p /var/lib/postgresql/data && chown -R postgres:postgres /var/lib/postgresql
RUN /usr/lib/postgresql/$(echo "${PG_Version}" | cut -d'-' -f1)/bin/initdb -D /var/lib/postgresql/data

USER root

WORKDIR /var/lib/postgresql/data
COPY ./conf/data/postgresql.conf ./postgresql.conf 
COPY ./conf/data/pg_hba.conf ./pg_hba.conf 
RUN chown -R postgres:postgres ./postgresql.conf && chown -R postgres:postgres ./pg_hba.conf
RUN chmod 600 ./postgresql.conf 
RUN chmod 600 ./pg_hba.conf



WORKDIR /etc/postgresql/$(echo "${PG_Version}" | cut -d'-' -f1)/main/
COPY ./conf/main/postgresql.conf ./postgresql.conf 
COPY ./conf/main/pg_hba.conf ./pg_hba.conf 
RUN chown -R postgres:postgres ./postgresql.conf && chown -R postgres:postgres ./pg_hba.conf
RUN chmod 644 ./postgresql.conf 
RUN chmod 640 ./pg_hba.conf

# iniciar PG
USER postgres
WORKDIR /var/lib/postgresql


# Copiar el archivo de Python al contenedor
USER root
WORKDIR /app
COPY test/checkPOSTGIS.py /app/
COPY conf/start.sh /app/


USER postgres
RUN /usr/lib/postgresql/$(echo "${PG_Version}" | cut -d'-' -f1)/bin/pg_ctl -D /var/lib/postgresql/data -l /var/lib/postgresql/logfile start &&\
    psql -c "SELECT 1;" &&\
    psql -c "CREATE USER usuario WITH PASSWORD 'pass';" && \
    psql -c "CREATE DATABASE postgis OWNER usuario;" &&\
    psql -d postgis -c "CREATE EXTENSION postgis;" && \
    psql -d postgis -c "CREATE EXTENSION postgis_topology;" ||\
    (cat /var/lib/postgresql/logfile && exit 1)

# Copiamos los datos iniciales a una ruta de respaldo dentro de la imagen
USER root
RUN cp -R /var/lib/postgresql/data /var/lib/postgresql/data_backup && chown -R postgres:postgres /var/lib/postgresql/data_backup
USER postgres


